# Generated by Django 4.0 on 2021-12-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('homepage', models.URLField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('runtime', models.SmallIntegerField()),
            ],
        ),
    ]
